ARG BUILD_FROM
FROM $BUILD_FROM

# Instalace Node.js
RUN apk add --no-cache nodejs npm

# Nastavení pracovního adresáře
WORKDIR /app

# Nejprve kopírujeme definice závislostí (kvůli cache)
COPY package.json ./

# Instalace závislostí
RUN npm install --production

# Kopírování zbytku aplikace (index.js a run.sh)
COPY . .

RUN chmod a+x run.sh

CMD [ "./run.sh" ]